GET http://localhost:4000/schools

###
POST http://localhost:4000/schools
Content-Type: application/json

{
    "schoolName": "Aix-en-provence"
}

###
POST http://localhost:4000/schools/1ecefe28-4015-405a-bd64-e88d60b04d26
Content-Type: application/json

{
    "schoolName": "Aix-en-provence__"
}

###
DELETE http://localhost:4000/schools/5a293933-7afe-43cb-a2a2-d16cfbe3df65