GET http://localhost:4000/skills


###
POST http://localhost:4000/skills
Content-Type: application/json

{
    "skillName": "C"
}

###
PUT http://localhost:4000/skills/a5c9bab1-bc62-4d2a-ac54-8397e2b534bc
Content-Type: application/json

{
    "skillName" : "C#"
}

###
DELETE http://localhost:4000/skills/a5c9bab1-bc62-4d2a-ac54-8397e2b534bc
Content-Type: application/json