GET http://localhost:4000/skills


###
POST http://localhost:4000/skills
Content-Type: application/json

{
    "skillName": "C"
}

###
PUT http://localhost:4000/skills/671e9c2f-db55-490f-a066-8b9be084cd08
Content-Type: application/json

{
    "skillName" : "C#"
}

###
DELETE http://localhost:4000/skills/e7588abb-7913-4ea2-82fc-ea791461d3a7
Content-Type: application/json